version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: npm
    directory: /examples/bundle
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tests/smoke/cjs
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tests/smoke/esm
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
